package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

var pathFiles = []string{
	"health.yaml",
	"auth.yaml",
	"auth_otp.yaml",
	"users.yaml",
	"groups.yaml",
	"expenses.yaml",
	"debts.yaml",
	"payments.yaml",
	"dashboard.yaml",
	"notifications.yaml",
}

var componentFiles = []string{
	"security.yaml",
	"responses.yaml",
	"schemas/common.yaml",
	"schemas/auth.yaml",
	"schemas/users.yaml",
	"schemas/groups.yaml",
	"schemas/expenses.yaml",
	"schemas/payments.yaml",
	"schemas/dashboard.yaml",
	"schemas/notifications.yaml",
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	baseDir := filepath.Join("api", "openapi")

	var output bytes.Buffer
	output.WriteString("# Code generated by `make openapi`; DO NOT EDIT.\n")

	root, err := readFragment(filepath.Join(baseDir, "root.yaml"))
	if err != nil {
		return err
	}
	output.Write(root)

	// File order is explicit so generated diffs stay stable and reviewable.
	output.WriteString("paths:\n")
	for _, file := range pathFiles {
		fragment, err := readFragment(filepath.Join(baseDir, "paths", file))
		if err != nil {
			return err
		}
		output.Write(fragment)
	}

	output.WriteString("components:\n")
	for _, file := range componentFiles {
		fragment, err := readFragment(filepath.Join(baseDir, "components", file))
		if err != nil {
			return err
		}
		output.Write(fragment)
	}

	return os.WriteFile(filepath.Join("api", "openapi.yaml"), output.Bytes(), 0o644)
}

func readFragment(path string) ([]byte, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if len(content) == 0 {
		return nil, fmt.Errorf("%s is empty", path)
	}
	if content[len(content)-1] != '\n' {
		return nil, fmt.Errorf("%s must end with a newline", path)
	}

	return content, nil
}
