// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token_hash, created_at, expires_at, revoked_at, last_used_at
`

type CreateAuthSessionParams struct {
	UserID           pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getActiveAuthSession = `-- name: GetActiveAuthSession :one
SELECT id, user_id, refresh_token_hash, created_at, expires_at, revoked_at, last_used_at
FROM auth_sessions
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveAuthSession(ctx context.Context, id pgtype.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, id)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE auth_sessions
SET refresh_token_hash = $2,
    last_used_at = now()
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, refresh_token_hash, created_at, expires_at, revoked_at, last_used_at
`

type RotateRefreshTokenParams struct {
	RefreshTokenHash   string
	RefreshTokenHash_2 string
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.RefreshTokenHash, arg.RefreshTokenHash_2)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}
