// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardTotalsForUser = `-- name: GetDashboardTotalsForUser :one
SELECT
    COALESCE(SUM(remaining_amount_minor) FILTER (
        WHERE debtor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_owe_minor,
    COALESCE(COUNT(*) FILTER (
        WHERE debtor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_owe_count,
    COALESCE(SUM(remaining_amount_minor) FILTER (
        WHERE creditor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_get_minor,
    COALESCE(COUNT(*) FILTER (
        WHERE creditor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_get_count
FROM debts
WHERE debtor_id = $1
   OR creditor_id = $1
`

type GetDashboardTotalsForUserRow struct {
	YouOweMinor int64
	YouOweCount int64
	YouGetMinor int64
	YouGetCount int64
}

func (q *Queries) GetDashboardTotalsForUser(ctx context.Context, debtorID pgtype.UUID) (GetDashboardTotalsForUserRow, error) {
	row := q.db.QueryRow(ctx, getDashboardTotalsForUser, debtorID)
	var i GetDashboardTotalsForUserRow
	err := row.Scan(
		&i.YouOweMinor,
		&i.YouOweCount,
		&i.YouGetMinor,
		&i.YouGetCount,
	)
	return i, err
}

const listDashboardPersonBalances = `-- name: ListDashboardPersonBalances :many
SELECT
    CASE WHEN d.debtor_id = $1 THEN 'owed' ELSE 'receivable' END::text AS balance_type,
    (CASE WHEN d.debtor_id = $1 THEN d.creditor_id ELSE d.debtor_id END)::uuid AS other_user_id,
    (CASE WHEN d.debtor_id = $1 THEN creditor.name ELSE debtor.name END)::text AS other_user_name,
    (CASE WHEN d.debtor_id = $1 THEN creditor.username ELSE debtor.username END)::text AS other_user_username,
    COALESCE(SUM(d.remaining_amount_minor), 0)::bigint AS remaining_amount_minor,
    COUNT(*)::bigint AS debt_count,
    -- Pending payments still need creditor review; clients use this flag to show review state.
    BOOL_OR(EXISTS (
        SELECT 1
        FROM payments p
        WHERE p.debt_id = d.id
          AND p.status = 'pending_confirmation'
    ))::boolean AS has_pending_payment
FROM debts d
JOIN users debtor ON debtor.id = d.debtor_id
JOIN users creditor ON creditor.id = d.creditor_id
WHERE (d.debtor_id = $1 OR d.creditor_id = $1)
  AND d.status IN ('accepted', 'partially_settled')
  AND d.remaining_amount_minor > 0
GROUP BY balance_type, other_user_id, other_user_name, other_user_username
ORDER BY balance_type ASC, remaining_amount_minor DESC, other_user_name ASC
`

type ListDashboardPersonBalancesRow struct {
	BalanceType          string
	OtherUserID          pgtype.UUID
	OtherUserName        string
	OtherUserUsername    string
	RemainingAmountMinor int64
	DebtCount            int64
	HasPendingPayment    bool
}

func (q *Queries) ListDashboardPersonBalances(ctx context.Context, debtorID pgtype.UUID) ([]ListDashboardPersonBalancesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardPersonBalances, debtorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardPersonBalancesRow
	for rows.Next() {
		var i ListDashboardPersonBalancesRow
		if err := rows.Scan(
			&i.BalanceType,
			&i.OtherUserID,
			&i.OtherUserName,
			&i.OtherUserUsername,
			&i.RemainingAmountMinor,
			&i.DebtCount,
			&i.HasPendingPayment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardUnsettledBalances = `-- name: ListDashboardUnsettledBalances :many
SELECT
    d.id,
    d.expense_id,
    e.title AS expense_title,
    d.debtor_id,
    debtor.name AS debtor_name,
    debtor.username AS debtor_username,
    d.creditor_id,
    creditor.name AS creditor_name,
    creditor.username AS creditor_username,
    d.remaining_amount_minor,
    d.status,
    d.updated_at
FROM debts d
JOIN expenses e ON e.id = d.expense_id
JOIN users debtor ON debtor.id = d.debtor_id
JOIN users creditor ON creditor.id = d.creditor_id
WHERE (d.debtor_id = $1 OR d.creditor_id = $1)
  AND d.status IN ('pending', 'accepted', 'partially_settled')
  AND d.remaining_amount_minor > 0
ORDER BY
    CASE WHEN d.debtor_id = $1 AND d.status = 'pending' THEN 0 ELSE 1 END,
    d.updated_at DESC,
    d.created_at DESC,
    d.id DESC
LIMIT 5
`

type ListDashboardUnsettledBalancesRow struct {
	ID                   pgtype.UUID
	ExpenseID            pgtype.UUID
	ExpenseTitle         string
	DebtorID             pgtype.UUID
	DebtorName           string
	DebtorUsername       string
	CreditorID           pgtype.UUID
	CreditorName         string
	CreditorUsername     string
	RemainingAmountMinor int64
	Status               string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListDashboardUnsettledBalances(ctx context.Context, debtorID pgtype.UUID) ([]ListDashboardUnsettledBalancesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardUnsettledBalances, debtorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardUnsettledBalancesRow
	for rows.Next() {
		var i ListDashboardUnsettledBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.ExpenseTitle,
			&i.DebtorID,
			&i.DebtorName,
			&i.DebtorUsername,
			&i.CreditorID,
			&i.CreditorName,
			&i.CreditorUsername,
			&i.RemainingAmountMinor,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
