// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardTotalsForUser = `-- name: GetDashboardTotalsForUser :one
SELECT
    COALESCE(SUM(remaining_amount_minor) FILTER (
        WHERE debtor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_owe_minor,
    COALESCE(COUNT(*) FILTER (
        WHERE debtor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_owe_count,
    COALESCE(SUM(remaining_amount_minor) FILTER (
        WHERE creditor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_get_minor,
    COALESCE(COUNT(*) FILTER (
        WHERE creditor_id = $1
          AND status IN ('accepted', 'partially_settled')
    ), 0)::bigint AS you_get_count
FROM debts
WHERE debtor_id = $1
   OR creditor_id = $1
`

type GetDashboardTotalsForUserRow struct {
	YouOweMinor int64
	YouOweCount int64
	YouGetMinor int64
	YouGetCount int64
}

func (q *Queries) GetDashboardTotalsForUser(ctx context.Context, debtorID pgtype.UUID) (GetDashboardTotalsForUserRow, error) {
	row := q.db.QueryRow(ctx, getDashboardTotalsForUser, debtorID)
	var i GetDashboardTotalsForUserRow
	err := row.Scan(
		&i.YouOweMinor,
		&i.YouOweCount,
		&i.YouGetMinor,
		&i.YouGetCount,
	)
	return i, err
}
