// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptDebt = `-- name: AcceptDebt :one
UPDATE debts
SET status = 'accepted',
    accepted_at = now()
WHERE id = $1
  AND debtor_id = $2
  AND status = 'pending'
RETURNING id, expense_id, debtor_id, creditor_id, original_amount_minor, remaining_amount_minor, status, accepted_at, rejected_at, settled_at, created_at, updated_at
`

type AcceptDebtParams struct {
	ID       pgtype.UUID
	DebtorID pgtype.UUID
}

func (q *Queries) AcceptDebt(ctx context.Context, arg AcceptDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, acceptDebt, arg.ID, arg.DebtorID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.DebtorID,
		&i.CreditorID,
		&i.OriginalAmountMinor,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    expense_id,
    debtor_id,
    creditor_id,
    original_amount_minor,
    remaining_amount_minor
)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, expense_id, debtor_id, creditor_id, original_amount_minor, remaining_amount_minor, status, accepted_at, rejected_at, settled_at, created_at, updated_at
`

type CreateDebtParams struct {
	ExpenseID           pgtype.UUID
	DebtorID            pgtype.UUID
	CreditorID          pgtype.UUID
	OriginalAmountMinor int64
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.ExpenseID,
		arg.DebtorID,
		arg.CreditorID,
		arg.OriginalAmountMinor,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.DebtorID,
		&i.CreditorID,
		&i.OriginalAmountMinor,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    group_id,
    title,
    description,
    total_amount_minor,
    currency,
    paid_by,
    split_type,
    receipt_url,
    expense_date,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, group_id, title, description, total_amount_minor, currency, paid_by, split_type, receipt_url, expense_date, created_by, created_at, updated_at
`

type CreateExpenseParams struct {
	GroupID          pgtype.UUID
	Title            string
	Description      pgtype.Text
	TotalAmountMinor int64
	Currency         string
	PaidBy           pgtype.UUID
	SplitType        string
	ReceiptUrl       pgtype.Text
	ExpenseDate      pgtype.Date
	CreatedBy        pgtype.UUID
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.TotalAmountMinor,
		arg.Currency,
		arg.PaidBy,
		arg.SplitType,
		arg.ReceiptUrl,
		arg.ExpenseDate,
		arg.CreatedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.TotalAmountMinor,
		&i.Currency,
		&i.PaidBy,
		&i.SplitType,
		&i.ReceiptUrl,
		&i.ExpenseDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpenseParticipant = `-- name: CreateExpenseParticipant :one
INSERT INTO expense_participants (expense_id, user_id, share_amount_minor)
VALUES ($1, $2, $3)
RETURNING id, expense_id, user_id, share_amount_minor, created_at
`

type CreateExpenseParticipantParams struct {
	ExpenseID        pgtype.UUID
	UserID           pgtype.UUID
	ShareAmountMinor int64
}

func (q *Queries) CreateExpenseParticipant(ctx context.Context, arg CreateExpenseParticipantParams) (ExpenseParticipant, error) {
	row := q.db.QueryRow(ctx, createExpenseParticipant, arg.ExpenseID, arg.UserID, arg.ShareAmountMinor)
	var i ExpenseParticipant
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.ShareAmountMinor,
		&i.CreatedAt,
	)
	return i, err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, expense_id, debtor_id, creditor_id, original_amount_minor, remaining_amount_minor, status, accepted_at, rejected_at, settled_at, created_at, updated_at
FROM debts
WHERE id = $1
`

func (q *Queries) GetDebtByID(ctx context.Context, id pgtype.UUID) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.DebtorID,
		&i.CreditorID,
		&i.OriginalAmountMinor,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebtReviewContext = `-- name: GetDebtReviewContext :one
SELECT d.status,
       EXISTS (
           SELECT 1
           FROM expenses e
           JOIN group_members gm ON gm.group_id = e.group_id
           WHERE e.id = d.expense_id
             AND gm.user_id = $2
             AND gm.role = 'owner'
       ) AS is_group_owner
FROM debts d
WHERE d.id = $1
`

type GetDebtReviewContextParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetDebtReviewContextRow struct {
	Status       string
	IsGroupOwner bool
}

func (q *Queries) GetDebtReviewContext(ctx context.Context, arg GetDebtReviewContextParams) (GetDebtReviewContextRow, error) {
	row := q.db.QueryRow(ctx, getDebtReviewContext, arg.ID, arg.UserID)
	var i GetDebtReviewContextRow
	err := row.Scan(&i.Status, &i.IsGroupOwner)
	return i, err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS (
    SELECT 1
    FROM group_members
    WHERE group_id = $1
      AND user_id = $2
)
`

type IsGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rejectDebt = `-- name: RejectDebt :one
UPDATE debts
SET status = 'rejected',
    rejected_at = now()
WHERE id = $1
  AND debtor_id = $2
  AND status = 'pending'
RETURNING id, expense_id, debtor_id, creditor_id, original_amount_minor, remaining_amount_minor, status, accepted_at, rejected_at, settled_at, created_at, updated_at
`

type RejectDebtParams struct {
	ID       pgtype.UUID
	DebtorID pgtype.UUID
}

func (q *Queries) RejectDebt(ctx context.Context, arg RejectDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, rejectDebt, arg.ID, arg.DebtorID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.DebtorID,
		&i.CreditorID,
		&i.OriginalAmountMinor,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reviewRejectedDebt = `-- name: ReviewRejectedDebt :one
UPDATE debts AS d
SET original_amount_minor = CASE WHEN $3::boolean THEN $4::bigint ELSE d.original_amount_minor END,
    remaining_amount_minor = CASE WHEN $3::boolean THEN $4::bigint ELSE d.original_amount_minor END,
    status = 'pending',
    accepted_at = NULL,
    rejected_at = NULL,
    settled_at = NULL
FROM expenses e
WHERE d.id = $1
  AND d.expense_id = e.id
  AND d.status = 'rejected'
  AND EXISTS (
      SELECT 1
      FROM group_members gm
      WHERE gm.group_id = e.group_id
        AND gm.user_id = $2
        AND gm.role = 'owner'
  )
RETURNING d.id, d.expense_id, d.debtor_id, d.creditor_id, d.original_amount_minor, d.remaining_amount_minor, d.status, d.accepted_at, d.rejected_at, d.settled_at, d.created_at, d.updated_at
`

type ReviewRejectedDebtParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	HasAdjustedAmount bool
	AmountMinor       int64
}

func (q *Queries) ReviewRejectedDebt(ctx context.Context, arg ReviewRejectedDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, reviewRejectedDebt,
		arg.ID,
		arg.UserID,
		arg.HasAdjustedAmount,
		arg.AmountMinor,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.DebtorID,
		&i.CreditorID,
		&i.OriginalAmountMinor,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
