// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at, updated_at
`

type CreateGroupParams struct {
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, role, joined_at
`

type CreateGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
	Role    string
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupForUser = `-- name: GetGroupForUser :one
SELECT g.id, g.name, g.created_by, g.created_at, g.updated_at
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE g.id = $1
  AND gm.user_id = $2
`

type GetGroupForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetGroupForUser(ctx context.Context, arg GetGroupForUserParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupForUser, arg.ID, arg.UserID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isGroupOwner = `-- name: IsGroupOwner :one
SELECT EXISTS (
    SELECT 1
    FROM group_members
    WHERE group_id = $1
      AND user_id = $2
      AND role = 'owner'
)
`

type IsGroupOwnerParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) IsGroupOwner(ctx context.Context, arg IsGroupOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupOwner, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupMembersForUser = `-- name: ListGroupMembersForUser :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.joined_at, u.name AS user_name, u.email AS user_email
FROM group_members gm
JOIN users u ON u.id = gm.user_id
JOIN group_members viewer ON viewer.group_id = gm.group_id
WHERE gm.group_id = $1
  AND viewer.user_id = $2
ORDER BY gm.joined_at ASC, gm.id ASC
`

type ListGroupMembersForUserParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

type ListGroupMembersForUserRow struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	JoinedAt  pgtype.Timestamptz
	UserName  string
	UserEmail string
}

func (q *Queries) ListGroupMembersForUser(ctx context.Context, arg ListGroupMembersForUserParams) ([]ListGroupMembersForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembersForUser, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersForUserRow
	for rows.Next() {
		var i ListGroupMembersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.created_by, g.created_at, g.updated_at
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC, g.id DESC
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE id = $1
)
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
