// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
}

type Debt struct {
	ID                   pgtype.UUID
	ExpenseID            pgtype.UUID
	DebtorID             pgtype.UUID
	CreditorID           pgtype.UUID
	OriginalAmountMinor  int64
	RemainingAmountMinor int64
	Status               string
	AcceptedAt           pgtype.Timestamptz
	RejectedAt           pgtype.Timestamptz
	SettledAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Expense struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	Title            string
	Description      pgtype.Text
	TotalAmountMinor int64
	Currency         string
	PaidBy           pgtype.UUID
	SplitType        string
	ReceiptUrl       pgtype.Text
	ExpenseDate      pgtype.Date
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ExpenseParticipant struct {
	ID               pgtype.UUID
	ExpenseID        pgtype.UUID
	UserID           pgtype.UUID
	ShareAmountMinor int64
	CreatedAt        pgtype.Timestamptz
}

type Group struct {
	ID        pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GroupMember struct {
	ID       pgtype.UUID
	GroupID  pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type Notification struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Type       string
	Title      string
	Body       string
	EntityType string
	EntityID   pgtype.UUID
	Metadata   []byte
	ReadAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Payment struct {
	ID          pgtype.UUID
	DebtID      pgtype.UUID
	PaidBy      pgtype.UUID
	ReceivedBy  pgtype.UUID
	AmountMinor int64
	Status      string
	Note        pgtype.Text
	ConfirmedAt pgtype.Timestamptz
	RejectedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Username     string
}
