// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyConfirmedPaymentToDebt = `-- name: ApplyConfirmedPaymentToDebt :one
UPDATE debts
SET remaining_amount_minor = remaining_amount_minor - $2,
    status = CASE
        WHEN remaining_amount_minor - $2 = 0 THEN 'settled'
        ELSE 'partially_settled'
    END,
    settled_at = CASE
        WHEN remaining_amount_minor - $2 = 0 THEN now()
        ELSE settled_at
    END
WHERE id = $1
  AND status IN ('accepted', 'partially_settled')
  AND remaining_amount_minor >= $2
RETURNING id, expense_id, debtor_id, creditor_id, original_amount_minor, remaining_amount_minor, status, accepted_at, rejected_at, settled_at, created_at, updated_at
`

type ApplyConfirmedPaymentToDebtParams struct {
	ID                   pgtype.UUID
	RemainingAmountMinor int64
}

func (q *Queries) ApplyConfirmedPaymentToDebt(ctx context.Context, arg ApplyConfirmedPaymentToDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, applyConfirmedPaymentToDebt, arg.ID, arg.RemainingAmountMinor)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.DebtorID,
		&i.CreditorID,
		&i.OriginalAmountMinor,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments
SET status = 'confirmed',
    confirmed_at = now()
WHERE id = $1
  AND status = 'pending_confirmation'
RETURNING id, debt_id, paid_by, received_by, amount_minor, status, note, confirmed_at, rejected_at, created_at, updated_at
`

func (q *Queries) ConfirmPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, confirmPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.PaidBy,
		&i.ReceivedBy,
		&i.AmountMinor,
		&i.Status,
		&i.Note,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (debt_id, paid_by, received_by, amount_minor, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, debt_id, paid_by, received_by, amount_minor, status, note, confirmed_at, rejected_at, created_at, updated_at
`

type CreatePaymentParams struct {
	DebtID      pgtype.UUID
	PaidBy      pgtype.UUID
	ReceivedBy  pgtype.UUID
	AmountMinor int64
	Note        pgtype.Text
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.DebtID,
		arg.PaidBy,
		arg.ReceivedBy,
		arg.AmountMinor,
		arg.Note,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.PaidBy,
		&i.ReceivedBy,
		&i.AmountMinor,
		&i.Status,
		&i.Note,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebtForPaymentMark = `-- name: GetDebtForPaymentMark :one
SELECT d.id,
       d.debtor_id,
       d.creditor_id,
       d.remaining_amount_minor,
       d.status,
       COALESCE((
           SELECT SUM(p.amount_minor)
           FROM payments p
           WHERE p.debt_id = d.id
             AND p.status = 'pending_confirmation'
       ), 0)::bigint AS pending_amount_minor
FROM debts d
WHERE d.id = $1
FOR UPDATE
`

type GetDebtForPaymentMarkRow struct {
	ID                   pgtype.UUID
	DebtorID             pgtype.UUID
	CreditorID           pgtype.UUID
	RemainingAmountMinor int64
	Status               string
	PendingAmountMinor   int64
}

func (q *Queries) GetDebtForPaymentMark(ctx context.Context, id pgtype.UUID) (GetDebtForPaymentMarkRow, error) {
	row := q.db.QueryRow(ctx, getDebtForPaymentMark, id)
	var i GetDebtForPaymentMarkRow
	err := row.Scan(
		&i.ID,
		&i.DebtorID,
		&i.CreditorID,
		&i.RemainingAmountMinor,
		&i.Status,
		&i.PendingAmountMinor,
	)
	return i, err
}

const getPaymentWithDebtForUpdate = `-- name: GetPaymentWithDebtForUpdate :one
SELECT p.id,
       p.debt_id,
       p.paid_by,
       p.received_by,
       p.amount_minor,
       p.status,
       p.note,
       p.confirmed_at,
       p.rejected_at,
       p.created_at,
       p.updated_at,
       d.status AS debt_status,
       d.remaining_amount_minor AS debt_remaining_amount_minor
FROM payments p
JOIN debts d ON d.id = p.debt_id
WHERE p.id = $1
FOR UPDATE OF p, d
`

type GetPaymentWithDebtForUpdateRow struct {
	ID                       pgtype.UUID
	DebtID                   pgtype.UUID
	PaidBy                   pgtype.UUID
	ReceivedBy               pgtype.UUID
	AmountMinor              int64
	Status                   string
	Note                     pgtype.Text
	ConfirmedAt              pgtype.Timestamptz
	RejectedAt               pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	DebtStatus               string
	DebtRemainingAmountMinor int64
}

func (q *Queries) GetPaymentWithDebtForUpdate(ctx context.Context, id pgtype.UUID) (GetPaymentWithDebtForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPaymentWithDebtForUpdate, id)
	var i GetPaymentWithDebtForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.PaidBy,
		&i.ReceivedBy,
		&i.AmountMinor,
		&i.Status,
		&i.Note,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DebtStatus,
		&i.DebtRemainingAmountMinor,
	)
	return i, err
}

const listBulkPaymentDebtsForUpdate = `-- name: ListBulkPaymentDebtsForUpdate :many
SELECT d.id,
       d.remaining_amount_minor
FROM debts d
WHERE d.debtor_id = $1
  AND d.creditor_id = $2
  AND d.status IN ('accepted', 'partially_settled')
  AND d.remaining_amount_minor > 0
  AND NOT EXISTS (
      SELECT 1
      FROM payments p
      WHERE p.debt_id = d.id
        AND p.status = 'pending_confirmation'
  )
ORDER BY d.updated_at ASC, d.created_at ASC, d.id ASC
FOR UPDATE
`

type ListBulkPaymentDebtsForUpdateParams struct {
	DebtorID   pgtype.UUID
	CreditorID pgtype.UUID
}

type ListBulkPaymentDebtsForUpdateRow struct {
	ID                   pgtype.UUID
	RemainingAmountMinor int64
}

func (q *Queries) ListBulkPaymentDebtsForUpdate(ctx context.Context, arg ListBulkPaymentDebtsForUpdateParams) ([]ListBulkPaymentDebtsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listBulkPaymentDebtsForUpdate, arg.DebtorID, arg.CreditorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBulkPaymentDebtsForUpdateRow
	for rows.Next() {
		var i ListBulkPaymentDebtsForUpdateRow
		if err := rows.Scan(&i.ID, &i.RemainingAmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForUser = `-- name: ListPaymentsForUser :many
SELECT
    p.id,
    p.debt_id,
    p.paid_by,
    payer.name AS paid_by_name,
    p.received_by,
    receiver.name AS received_by_name,
    p.amount_minor,
    p.status,
    p.note,
    p.confirmed_at,
    p.rejected_at,
    p.created_at,
    p.updated_at,
    d.expense_id,
    e.title AS expense_title,
    d.remaining_amount_minor AS debt_remaining_amount_minor,
    d.status AS debt_status
FROM payments p
JOIN debts d ON d.id = p.debt_id
JOIN expenses e ON e.id = d.expense_id
JOIN users payer ON payer.id = p.paid_by
JOIN users receiver ON receiver.id = p.received_by
WHERE (p.paid_by = $1 OR p.received_by = $1)
  AND ($2::text IS NULL OR p.status = $2::text)
  AND (
      $3::text IS NULL
      OR ($3::text = 'sent' AND p.paid_by = $1)
      OR ($3::text = 'received' AND p.received_by = $1)
  )
ORDER BY
    CASE WHEN p.status = 'pending_confirmation' AND p.received_by = $1 THEN 0 ELSE 1 END,
    p.updated_at DESC,
    p.created_at DESC,
    p.id DESC
`

type ListPaymentsForUserParams struct {
	PaidBy      pgtype.UUID
	Status      pgtype.Text
	PaymentType pgtype.Text
}

type ListPaymentsForUserRow struct {
	ID                       pgtype.UUID
	DebtID                   pgtype.UUID
	PaidBy                   pgtype.UUID
	PaidByName               string
	ReceivedBy               pgtype.UUID
	ReceivedByName           string
	AmountMinor              int64
	Status                   string
	Note                     pgtype.Text
	ConfirmedAt              pgtype.Timestamptz
	RejectedAt               pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	ExpenseID                pgtype.UUID
	ExpenseTitle             string
	DebtRemainingAmountMinor int64
	DebtStatus               string
}

// Creditor-side pending payments are review tasks, so keep them at the top of the inbox.
func (q *Queries) ListPaymentsForUser(ctx context.Context, arg ListPaymentsForUserParams) ([]ListPaymentsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsForUser, arg.PaidBy, arg.Status, arg.PaymentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsForUserRow
	for rows.Next() {
		var i ListPaymentsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.PaidBy,
			&i.PaidByName,
			&i.ReceivedBy,
			&i.ReceivedByName,
			&i.AmountMinor,
			&i.Status,
			&i.Note,
			&i.ConfirmedAt,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpenseID,
			&i.ExpenseTitle,
			&i.DebtRemainingAmountMinor,
			&i.DebtStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPayment = `-- name: RejectPayment :one
UPDATE payments
SET status = 'rejected',
    rejected_at = now()
WHERE id = $1
  AND status = 'pending_confirmation'
RETURNING id, debt_id, paid_by, received_by, amount_minor, status, note, confirmed_at, rejected_at, created_at, updated_at
`

func (q *Queries) RejectPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, rejectPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.PaidBy,
		&i.ReceivedBy,
		&i.AmountMinor,
		&i.Status,
		&i.Note,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
