// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, email, password_hash, verification_deadline)
VALUES ($1, $2, $3, $4, now() + interval '7 days')
RETURNING id, name, username, email, password_hash, email_verified_at, verification_deadline, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	Username     string
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	PasswordHash         string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.VerificationDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, username, email, password_hash, email_verified_at, verification_deadline, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	PasswordHash         string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.VerificationDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, password_hash, email_verified_at, verification_deadline, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	PasswordHash         string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.VerificationDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email, password_hash, email_verified_at, verification_deadline, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	PasswordHash         string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.VerificationDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users
SET email_verified_at = now()
WHERE id = $1
RETURNING id, name, username, email, email_verified_at, verification_deadline, created_at, updated_at
`

type MarkEmailVerifiedRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) (MarkEmailVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i MarkEmailVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.VerificationDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, name, username, email, password_hash, email_verified_at, verification_deadline, created_at, updated_at
FROM users
WHERE username LIKE replace($1::text, '_', '\_') || '%' ESCAPE '\'
ORDER BY username ASC
LIMIT $2
`

type SearchUsersByUsernameParams struct {
	Column1 string
	Limit   int32
}

type SearchUsersByUsernameRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	PasswordHash         string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

// Treat underscores as literal username characters instead of SQL LIKE wildcards.
func (q *Queries) SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]SearchUsersByUsernameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsername, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersByUsernameRow
	for rows.Next() {
		var i SearchUsersByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.EmailVerifiedAt,
			&i.VerificationDeadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users
SET username = $2
WHERE id = $1
RETURNING id, name, username, email, password_hash, email_verified_at, verification_deadline, created_at, updated_at
`

type UpdateUserUsernameParams struct {
	ID       pgtype.UUID
	Username string
}

type UpdateUserUsernameRow struct {
	ID                   pgtype.UUID
	Name                 string
	Username             string
	Email                string
	PasswordHash         string
	EmailVerifiedAt      pgtype.Timestamptz
	VerificationDeadline pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (UpdateUserUsernameRow, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.ID, arg.Username)
	var i UpdateUserUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.VerificationDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
